version: '3.8'

services:
  selenoid:
    image: "aerokube/selenoid"
    ports:
      - "4444:4444"
    volumes:
      - "./config.json:/etc/selenoid/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/config.json"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  autotests:
    build: .
    depends_on:
      - selenoid
    volumes:
      - ./allure-results:/app/allure-results
    command: ["pytest"]